version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "5173:5173"
    environment:
       - CHOKIDAR_USEPOLLING=true